-- AlterTable
ALTER TABLE `Herramienta` MODIFY `registro` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `Material` MODIFY `registro` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3);
